---
- hosts: selectica_production_area
  user: ec2-user
  become: true
  tasks:
   
   - name: Copy file remotely
     copy: src=/home/gtkachenko/myscripts/clear_sssd_cache.sh dest=/home/ec2-user owner=ec2-user group=ec2-user mode=0744
